feat(lhls): add lhls support
alibaba/CicadaPlayer pull request #501
Opened 2020-11-24 09:14 UTC by kongjianneu

2020-11-24 12:51 UTC, pingkai requested changes

2020-11-24 12:51 UTC, pingkai commented on framework/demuxer/demuxer_service.cpp
> +        return (!mDemuxerPtr->isPlayList()) || mDemuxerPtr->isRealTimeStream(index);
1. If not a playList demuxer, then it is a realtime stream ?
2. Is the parameter index usefull?

2020-11-24 12:51 UTC, pingkai commented on framework/demuxer/play_list/HLSStream.cpp
> +
use git clang format to format the code

2020-11-24 12:51 UTC, pingkai commented on framework/demuxer/play_list/HLSStream.cpp
> +            if (move_ret == 1) {
What the mean of 1? Use a enum or bool?

2020-11-25 06:17 UTC, kongjianneu commented on framework/demuxer/play_list/HLSStream.cpp
> +            if (move_ret == 1) {
modified

2020-11-25 06:17 UTC, kongjianneu commented on framework/demuxer/play_list/HLSStream.cpp
> +
modified

2020-11-25 06:38 UTC, pingkai approved these changes

2020-11-25 09:31 UTC, merged